version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/app
    steps:
      - checkout
      # Install MongoDB Compass
      - run:
          name: Install MongoDB Compass
          command: |
            wget https://downloads.mongodb.com/compass/mongodb-compass_1.28.1_amd64.deb
            sudo dpkg -i mongodb-compass_1.28.1_amd64.deb

      # Install dependencies
      - run: npm install

      # Run tests
      - run: npm test

  # Define services (MongoDB Compass)
  services:
    mongodb-compass:
      image: circleci/mongo:4.4.8
      ports:
        - "27017:27017"
