version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/app
    steps:
      - checkout
      # Install MongoDB
      - run:
          name: Install MongoDB
          command: |
            sudo apt-get update
            sudo apt-get install -y mongodb
            mkdir -p ~/mongodb/data
            mongod --dbpath ~/mongodb/data --fork --logpath ~/mongodb/log.txt
            sleep 10 # wait for MongoDB to start

      # Install dependencies
      - run: npm install

      # Run tests
      - run: npm test

  # Define services (MongoDB)
  services:
    mongodb:
      image: mongo:latest
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: micka
        MONGO_INITDB_ROOT_PASSWORD: 
