"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
import express_1 from "express";
import postController_1 from "../controllers/postController";
var router = express_1.default.Router();
router.get("/posts", postController_1.getPost);
router.post("/posts", postController_1.addNewPost);
router.get("/posts/:id", postController_1.individualPost);
router.delete("/posts/:id", postController_1.deleteItem);
exports.default = router;
